module.exports = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  SEARCHING_GARAGE: "SEARCHING_GARAGE",
  GARAGE_ASSIGNED: "GARAGE_ASSIGNED",
  CONFIRMED: "CONFIRMED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
};