module.exports = {
  CREDIT: "CREDIT",
  DEBIT: "DEBIT",

  RECHARGE: "RECHARGE",

  REFUND: "REFUND",

  CASHBACK: "CASHBACK",

  BOOKING_PAYMENT: "BOOKING_PAYMENT",

  BOOKING_REFUND: "BOOKING_REFUND",

  GARAGE_ACCEPT_FEE: "GARAGE_ACCEPT_FEE",

  SOS_DEDUCTION: "SOS_DEDUCTION",
};