services:
  backend:
    build: ./server
    container_name: rovauto-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    container_name: rovauto-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always